// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oddzcwbyquccislpkple.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kZHpjd2J5cXVjY2lzbHBrcGxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwNDQ5MjAsImV4cCI6MjA2NzYyMDkyMH0.7C5CaTm7eNMlm7qaX0rQcPwcdDi0LBMye7Dv3_6YXuU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});